Products Web API with test cases
Purvajagopalakrishnan/ProductsWebAPIWithTDD pull request #1
Opened 2020-07-23 17:58 UTC by Purvajagopalakrishnan

2020-07-24 07:11 UTC, Harimaharajan requested changes
You have to write test cases for all layers
Service and Repository
Fo Test project, Try and follow the same folder structures like in your main API project, just append Tests to it. 
ControllerTests
ServiceTests

Also Its best if the Filename also matches for tests, trailing by **Tests**

2020-07-24 07:11 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi/Interface/IProductService.cs
> +        Product GetProducts(int productId);
GetProductById

2020-07-24 07:11 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi.Tests/ProductsTest.cs
> +            var productService = new Mock<IProductService>();
You can create class-level variables for these and instantiate them in the constructor. That would reduce two lines of codes in each of  your tests
Please do that in all your test cases

2020-07-24 07:11 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi.Tests/ProductsTest.cs
> +            var productService = new Mock<IProductService>();
For now, please add
// arrange
// act
// assert 
respectively in all tests.

2020-07-24 07:11 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi/Controllers/ProductsController.cs
> +                throw new HttpResponseException(HttpStatusCode.InternalServerError); ;
Never return exception from an API.
Always return responses like
BadRequest()
NotFound()
like those
https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.1

2020-07-24 07:11 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi/Controllers/ProductsController.cs
> +                Product product = _productService.GetProducts(productId);
prefer var instead of concrete types

2020-07-24 07:11 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi/Controllers/ProductsController.cs
> +        }
Line breaks between methods. always

2020-07-24 07:11 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi/Controllers/ProductsController.cs
> +        [Microsoft.AspNetCore.Mvc.HttpPut]
I'd like this to be just

[Route("{productId:int}")]
[HttpGet]
and move the namespace out of it.
Can you do that?

2020-07-24 08:33 UTC, Purvajagopalakrishnan commented on ProductsWebApi/ProductsWebApi.Tests/ProductsTest.cs
> +            var productService = new Mock<IProductService>();
Got it. I will create a class-level variable and also add arrange, act, and assert.

2020-07-27 15:41 UTC, Harimaharajan requested changes

2020-07-27 15:41 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi/Controllers/ProductsController.cs
> +        [HttpPut("/api/products/{id}")]
You can move the `/api/products/` to the controller Route. Since it is getting repeated in all endpoints.
and make sure the endpoint works

2020-07-27 15:41 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi.Tests/ProductsServiceTest.cs
> +        {
👏

2020-07-27 15:41 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi.Tests/ProductsServiceTest.cs
> +        private Product productRequestObj = null;
Always prefer full naming. 
productRequestObject.
In this case, 
it can be productRequest

2020-07-27 15:41 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi.Tests/ProductsServiceTest.cs
> +            var expextedResult = _fixture.Build<Product>().CreateMany().ToList();
// arrange 
// act 
// assert
and always try and leave line breaks between them if possible.

2020-07-27 15:41 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi/Service/ProductService.cs
> +        public ProductsService(IProductsService productsService)
What's this???
Why are injecting IProductService in service. 🤔 
Shouldn't this be repository?

2020-07-27 15:41 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi/Repository/ProductRepository.cs
> +        public ProductRepository(IProductRepository productRepository)
same here. Please read through about Dependency Injection and why it is used.

2020-07-27 15:41 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi.Tests/ProductsControllerTest.cs
> +        private readonly Mock<IProductsService> _mockproductsService;
_mockProductsService

2020-07-27 15:41 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi.Tests/ProductsControllerTest.cs
> +            var expectedResult = _fixture.Build<Product>().CreateMany().ToList();
// arrange 
// act
// assert

2020-07-27 15:41 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi.Tests/ProductsControllerTest.cs
> +            var expectedResult = _fixture.Build<Product>().Create();
you can directly do _fixture.Create<Product>();

2020-07-28 12:28 UTC, Harimaharajan requested changes

2020-07-28 12:28 UTC, Harimaharajan commented on ProductsWebApi/ProductsWebApi.Tests/ProductsControllerTest.cs
> +
Why new line between each LOC 🤔 
I meant new line only between arrange act and assert as a sections

//arrage
..
..

//act
...
....
...

//assert
..
..
...
..

2020-07-28 13:01 UTC, Harimaharajan approved these changes

2020-07-28 13:09 UTC, merged